### ISSUE TITLE
linksnatch:latest does not exist

### ISSUE THREAD

**Issue by mariushosting** [obiequack/linksnatch-docker#1]
linksnatch:latest does not exist.

**Comment by eternalevelyn** [comment]
Hmmmmm. You need to build the image beforehand as is mentioned in the readme- in the git repo, run 
```
docker build . -t linksnatch:latest
```
 If that doesn't work, please do provide me with more details

**Comment by mariushosting** [comment]
Better to provide one without needing for user to build it :-)

**Comment by eternalevelyn** [comment]
I know that, but I haven't yet uploaded it to the Docker Hub- so until I get around to that, please build the image, it's just one command. Also, I've yet to test the full setup- but I will this upcoming weekend. Thanks (and respect), your blog on Synology has sped up my efforts in fixing certain things on my DS920+ a hundredfold. :)
