### ISSUE TITLE
Error by execute install.sh

### ISSUE THREAD

**Issue by Boebbele** [obiequack/linksnatch-docker#2]
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

invalid argument "linksnatch:latest\r" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
[+] Running 0/1
 ⠿ linksnatch Error                                                        2.5s
Error response from daemon: pull access denied for linksnatch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by eternalevelyn** [comment]
Should be fixed now with a new commit.
