### ISSUE TITLE
Error while execute docker-compose up -d

### ISSUE THREAD

**Issue by Boebbele** [obiequack/linksnatch-docker#3]
[+] Running 0/1
 ⠿ linksnatch Error                                                        1.8s
Error response from daemon: pull access denied for linksnatch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by eternalevelyn** [comment]
You're running docker-compose up -d without building the image first (`docker build -q . -t linksnatch:latest`)
